#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    Nov 11, 2018 03:57:06 PM CET  platform: Windows NT

import sys
import gui1
import subprocess
import threading, time
import psutil,time
import base64
import re
global block,checking_system,input2parsed,iterations,run_block,thread_limit,sqlcmd_mode

MEMORY_LIMIT_PERCENT=60
CPU_LIMIT_PERCENT=30
block=False
run_block=False
thread_limit=10

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True



def ananas():
    global CREATE_NO_WINDOW,block,input2parsed,run_block,querry,user,passw,CHECK_PER,sqlcmd_mode
    CREATE_NO_WINDOW = 0x08000000
    CHECK_PER=10
    if not run_block:
        querry=w.Scrolledtext2.get(0.0,"end").replace('\n', ' ')
        user=w.Entry1.get().replace(' ', '').replace('\n', '')
        passw=w.Entry2.get().replace(' ', '').replace('\n', '').encode('base64')
        input2=w.Scrolledtext1.get(0.0,"end").encode("ascii")
        sqlcmd_mode=False
        if len(input2)>1 and len(passw)>0 and len(user)>0 and len(querry)>1 and "-Querry-" not in querry and "Username" not in user and "-Hosts-" not in input2:
            run_block=True
            w.Scrolledtext3.delete(1.0,"end")
            w.Button1.configure(text="Running")
            input2parsed=input2.splitlines()
            if re.search("xp_cmdshell",querry,re.IGNORECASE):
                querry=querry.replace('xp_cmdshell', 'exec xp_cmdshell')
                querry=querry.replace('"', '""')
                sqlcmd_mode=True
            threading.Thread(target=check_system).start()
            threading.Thread(target=launcher).start()

        

def launcher():
    global input2parsed,iterations,CHECK_PER,block,thread_limit
    iterations=0
    for line in input2parsed:
        if len(line)>0:
            if block or threading.activeCount()>thread_limit:
                while threading.activeCount()>6:
                    time.sleep(1)
            thread = threading.Thread(target=procedure,args=(line.splitlines()))
            thread.start()
        else:
            pass
        if iterations%20==0 and iterations!=0 and len(input2parsed)!=(iterations+1):
            time.sleep(0.2)
        iterations+=1



def procedure(dest):
    global iterations,input2parsed,run_block,querry,user,passw,sqlcmd_mode
    try:
        if sqlcmd_mode:
            output2 = subprocess.check_output("sqlcmd -S "+dest+" -U "+user+" -P "+passw.decode('base64')+" -Q "+'"'+querry+'"'+" -l 10 -t 30 -s "+'"'+'|'+'"'+" && exit",shell=True, bufsize=-1 , stderr=subprocess.STDOUT, stdin=subprocess.PIPE, close_fds=False, creationflags=CREATE_NO_WINDOW).decode("utf-8")
        else:
            output2 = subprocess.check_output("sqlcmd -S "+dest+" -U "+user+" -P "+passw.decode('base64')+" -Q "+'"'+"SET NOCOUNT ON;"+querry+'"'+" -y 32 -Y 32 -l 10 -t 60 -s "+'"'+'|'+'"'+" && exit",shell=True, bufsize=-1 ,stderr=subprocess.STDOUT, stdin=subprocess.PIPE, close_fds=False, creationflags=CREATE_NO_WINDOW).decode("utf-8")
        w.Scrolledtext3.insert("end",'\n'+"++++++++++++++++++++++++++++++++++++++++"+'\n'+"--------------------"+"Output from: "+dest+'\n'+output2)
    except subprocess.CalledProcessError as e:
        w.Scrolledtext3.insert("end",'\n'+"++++++++++++++++++++++++++++++++++++++++"+'\n'+"--------------------"+"Output from: "+dest+ " (ERROR!)"+'\n'+e.output)
    if iterations>=len(input2parsed):
        w.Button1.configure(text='''GO''')
        w.Scrolledtext3.see("end")
        run_block=False
    else:
        run_block=True



def check_system():
    global run_block,block,thread_limit
    while run_block:
        current_cpu=psutil.cpu_percent(interval=0.2, percpu=False)
        if psutil.virtual_memory().percent<MEMORY_LIMIT_PERCENT and current_cpu<CPU_LIMIT_PERCENT:
            block=False
            thread_limit+=2
        else:
            block=True
            thread_limit-=2

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level,run_block,input2parsed
    input2parsed = []
    run_block=False
    top_level.destroy()
    top_level = None


if __name__ == '__main__':
    import gui1.py
    gui1.py.vp_start_gui()




